### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by mmohamedbasith** [pnp/sp-dev-solutions#303]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Search Result webpart , detailed List have 'Title' column which is sortable by default. Clicking on sort should sort records in all pages.

#### Observed Behavior

detailed List have 'Title' column which is sortable by default. Clicking on sort icon , perform sorting of records present in the particular page . It is not considering records in other pages.

Also Sorting is perfomed with ACSII logic (i.e A-Za-z1-9 ) and case sensitive. (which i can understand thats how OOTB Search perform sort as well. Need a way to hide sort icon for Title in detailed view)

**Comment by NeoLegolas** [comment]
@mmohamedbasith You can user one of many RefinableStrings Manageproperty and map your Title crawl properties to it. Once done you can use that Property to sort in your webpart. I've done the same and it solved my issue.

**Comment by mmohamedbasith** [comment]
@NeoLegolas  I don't have issues with how to make title sortable . The problem is with the way how the title is getting sorted. 
SharePoint Search default performs ASCII Sort (Not alphabetical sort) i.e Capital letter alphabets will be sorted first then small letter alphabets  [A-Za-z0-9]. 

I dont want to give Title sort functionality to customer. So i was looking to hide the sortablity of Title which is getting displayed in detailed view of the webpart. @wobba  thanks for your response i missed the option to hide . I have hidden the sort for title.
