### ISSUE TITLE
Query Rules : Result blocks and promoted results ::: Need suggestions and workaround

### ISSUE THREAD

**Issue by pravin080317** [pnp/sp-dev-solutions#397]
I can see in #161 that result blocks are not supported in the search results webpart.  please suggest if this still the case or any recent updates on it.

1. we have a requirement to display search results like the below format, when a user click on All section in the vertical webpart. Basically we have sections like All, People, Applications, Documents. when a user clicks on ALL , the requirement is to show the results like modern sharepoint search OOTB does. like kind of displaying the top matching 5 people section and top matching 5 application section and after that we need to display documents one by one. 

please refer the below image and kindly let me know if this is achievable using pnp modern search webpart.

![image](https://user-images.githubusercontent.com/35328578/81174008-a3a0bd00-8fbe-11ea-99f9-0fefd2432c91.png)

2. i know we can use handlebars in the result types or in custom template to style the search results. but would like to know whether it id possible to use column formatting json style option in search results.

**Comment by wobba** [comment]
You should be able to loop over `secondaryResults` or `promotedResults` instead of `items` in your template.

**Comment by pravin080317** [comment]
@wobba : thanks for the response. 

i can see three types of results in search results. 1. RefinementResults 2. RelevantResults 3. SecondaryResults.   
can you please help me to understand the differences between these results. From the names i can relate like RelevantResults are ones that contains actual items of search. RefinementResults are the ones that contains the items once we used refiner webpart. Please correct me if my understanding is wrong. 

![image](https://user-images.githubusercontent.com/35328578/81293200-8b966f80-908a-11ea-8fa6-7d66a93a89ec.png)

**Comment by wobba** [comment]
Sorry.. you should head over to github.com/microsoft-search/pnp-modern-search and get the solution and file issues there. The project no longer lives here.
