### ISSUE TITLE
MultilingualPagesConverter: Incorrect feature ID for PnP feature?

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/sp-dev-solutions#408]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Assuming this code checks both the "old" SPFx PnP solution feature ID and the "new" OOTB feature ID those IDs should be different, **but are identical**:

![image](https://user-images.githubusercontent.com/3469970/83649482-8a882d80-a5b7-11ea-9926-dc9d2123de62.png)

https://github.com/pnp/sp-dev-solutions/blob/79cbfb72181ba7ad55e7c8e238dfc1117deadc2d/solutions/MultilingualPages/Converter/MultilingualPagesConverter/Program.cs#L122

https://github.com/pnp/sp-dev-solutions/blob/79cbfb72181ba7ad55e7c8e238dfc1117deadc2d/solutions/MultilingualPages/Converter/MultilingualPagesConverter/Program.cs#L132

#### Observed Behavior

The code as is only checks for the OOTB feature to be enabled. This probably makes no harm but looks like an error. Or is this intentional?

**Comment by heinrich-ulbricht** [comment]
The correct PnP feature ID is shown here:

https://github.com/pnp/sp-dev-solutions/blob/79cbfb72181ba7ad55e7c8e238dfc1117deadc2d/solutions/MultilingualPages/SPFxExt/config/package-solution.json#L13

**Comment by juliemturner** [comment]
Yes, that's a bug but the fix is not changing the id but rather using the AppManager, the actual code is in the cleanup function so it's just a matter of moving a copy up to do the check.  Also, for your PR yes, sorry it appears that the .gitignore didn't have the `packages` folder in it. I will update the .gitignore.  Since I'm going to have to do a PR anyway to fix this bug I'll just close your PR and remove that folder at the same time.  Thanks for your feedback and review, it's very helpful.

**Comment by heinrich-ulbricht** [comment]
@juliemturner  Ok cool. I'll have another PR coming up fixing two bugs prventing us from converting pages. I have the app ID of the PnP solution in there - should I leave it in or revert this specific change?

**Comment by juliemturner** [comment]
That code with that ID in it doesn't work as intended... the intention of the code is to see if that feature has been deployed to that site collection and the code that's in there won't work for that.  I had fixed the disable app piece of the equation but never went back and fixed the check function.  What that would do is just see if the feature is installed in the tenant app catalog not check if the feature is enabled in the site... it's a very odd API to work with honestly and it took me a while to figure out how to do it properly.

**Comment by heinrich-ulbricht** [comment]
@juliemturner In my understanding the web feature is activated as soon as the app is added. The feature is responsible for activating the custom action that loads the application customizer JS code. After removing the app the feature is gone. So the presence of this feature should indicate the installed app.
But I'll leave it out for now since other issues are more pressing and I hope I got it right over there -> #410

**Comment by heinrich-ulbricht** [comment]
Nice, app manager is so much cleaner!
