### ISSUE TITLE
Pass URL scope to central modern search site. u?={contexturl} 

### ISSUE THREAD

**Issue by PaulvandeSande** [pnp/sp-dev-solutions#409]
- [X] Question

In the classic search options I can pass the siteURL to the central search page to limit my search to the project site it is called from: /result.aspx?u={contexturl}

I'm familiar with pnp modern search webpart functionality that uses the  # in the URL to pass keywords to another search site.

My question is how can I reproduce the u?={contexturl} functionality so that the central search site is limited to a site url?

Greetings, Paul van de Sande

**Comment by wobba** [comment]
You can pass in any query parameter and use that as part of your query template. See https://microsoft-search.github.io/pnp-modern-search/search-parts/search-results/#url-token-and-request-properties

**Comment by PaulvandeSande** [comment]
Hello Mikael,

I have multiple project sites and I only want to use 1 serach result site. In this site I want to filter on the project site url.

The only Query parameter name that works for me is ‘q’ and that only passes the value of the search box to the new page I’m opening.

As soon as I use options like {Site} it is not passing the URL of the new site.

The query variables mentioned in your URL/documentation only work in the page that I openend. {Site} is the site of the new page opened and not the project site.

How can I pass multiple values to my new opened search page?

  1.  Search box content (ok this works)
  2.  The URL of the project site where the search box value was entered. So that I can use it as a query template filter.

(searchterms} path:{Site}

{site} = project site.



Met vriendelijke groet | Kind regards,
Paul van de Sande
Cadac Group PP&M BV
Business Consultant

+31 88 9322 467
paulvandesande@cadac.com<mailto:paulvandesande@cadac.com>
www.cadac.com<http://www.cadac.com>

Nieuw Eyckholt 282
6419 DJ Heerlen

[http://info.cadac.com/eml-img/ppm-1.png]<http://www.cadac.com/email-ppm-1>
[http://info.cadac.com/eml-img/ppm-2.png]<http://www.cadac.com/email-ppm-2>
[http://info.cadac.com/eml-img/ppm-3.png]<http://www.cadac.com/email-ppm-3>
[http://info.cadac.com/eml-img/ppm-4.png]<http://www.cadac.com/email-ppm-4>

**Comment by wobba** [comment]
I get what you want now. Thing is {contexturl} in classic was evaluated client side, which means you have to pass that over somehow to the target page as a query param which you can use in the template...{site} evaluates to the site you are on. What might work if implemented is using the referrer URL as a variable..with some trimming logic.

There has been asks that the oob search box can support these variables, but don't know if it will happen. They were never documented in classic either, and part of the classic SP page structure internally. If we do add support for it OOB, I'll make sure it's documented.

**Comment by PaulvandeSande** [comment]
Thanks Mikael

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Mikael Svenson <notifications@github.com>
Verzonden: Friday, June 5, 2020 9:45:19 PM
Aan: pnp/sp-dev-solutions <sp-dev-solutions@noreply.github.com>
CC: Paul van de Sande <paulvandesande@cadac.com>; Author <author@noreply.github.com>
Onderwerp: Re: [pnp/sp-dev-solutions] Pass URL scope to central modern search site. u?={contexturl} (#409)


I get what you want now. Thing is {contexturl} in classic was evaluated client side, which means you have to pass that over somehow to the target page as a query param which you can use in the template...{site} evaluates to the site you are on. What might work if implemented is using the referrer URL as a variable..with some trimming logic.

There has been asks that the oob search box can support these variables, but don't know if it will happen. They were never documented in classic either, and part of the classic SP page structure internally. If we do add support for it OOB, I'll make sure it's documented.
