### ISSUE TITLE
MultilingualPagesConverter: Conversion fails to detect master pages and translation pages in certain circumstances

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/sp-dev-solutions#410]
#### Category
- [ ] Question
- [x] Bug
- [x] Enhancement

#### Expected or Desired Behavior

I expect the MultilingualPagesConverter to detect master and translation pages properly.

I expect to use the MultilingualPagesConverter to create master pages from pages with language different from the default site language.

(This is actually a bug fix and a feature request in one ticket. Sorry.)

#### Observed Behavior

For some settings master pages and translation pages are not properly detected.

#### Steps to Reproduce

Create the following setup:

* Create a site with default language **en-us**
* Add old PnP solution MultilangualPagesConverter; configure it to support at least the languages **en-gb** and **de-de**, NOT en-us
* Create language master pages with master language **de-de** (using the PnP solution)
* Create translation pages for language **en-gb** (yes, not en-us) (using the PnP solution)
* Enable the new OOTB MUI feature

Run the converter. It will fail to work because the old masters are en-gb. Now I changed the code to make this work. And then ran into a bug that prevented the translation pages to be properly detected while converting the old **en**-translation pages to be the new **en**-master pages.

Pull request incoming where you can see two lines of fixed bugs and a language override feature.

**Comment by heinrich-ulbricht** [comment]
@juliemturner Uhm this was a quick close. Was this by accident or intentional?

**Comment by juliemturner** [comment]
No, I accidentily referenced the wrong number in the PR because I had both of your issues open in my browser and picked the wrong one. 

Ok, so what you're saying is this fix is meant to fix pages where the user decided on a language other than the site's languages as the default one for their pages.  I got it.  The solution was written for one client where that wasn't the case so this was definitely not a scenario I foresaw.

**Comment by heinrich-ulbricht** [comment]
No problem. Yes we unfortunately have a customer who has a mix of different languages leading to this "override" to be necessary. Seems to work with the change.
And there are two ID comparisons that did not work for us leading to page connections not being detected properly.

**Comment by juliemturner** [comment]
Looking at your changes I agree with everything for the most part but this change has me concerned as the "MasterTranslationPage", although should be the items ID is not as reliable and I think that's a bad page translation and wouldn't want to rely on it... this would be an instance where I'd want to trap the situation not assume "MasterTranslationPage" is correct.. What's the thinking there.  

TO
   ```
   var masterPage = masterPages.Where(m => m["MasterTranslationPage"].ToString() == trans["MasterTranslationPage"].ToString());
   ```
FROM
   ```
   var masterPage = masterPages.Where(m => m.Id.ToString() == trans["MasterTranslationPage"].ToString());
   ```

**Comment by heinrich-ulbricht** [comment]
@juliemturner My interpretation here is this:
The problem seems to be that - when promoting translation pages to master pages in a previous step - the `MasterTranslationPage` is not being updated to themselves. 
So when pointing translation pages to the newly appointed master page here:
https://github.com/pnp/sp-dev-solutions/blob/cdc267cb6683a2b7c1b9c424c905e37e3da618e6/solutions/MultilingualPages/Converter/MultilingualPagesConverter/Program.cs#L369

Shoudln't the `MasterTranslationPage` of the (former translation page, now master page) be updated as well to point to themselves? Then the code change you are referring to would probably not be necessary.

Does this make sense? I confess the whole translation and master conversion made my head spin a bit :)

**Comment by juliemturner** [comment]
I agree that makes more sense to me, because it's deliberate.
