### ISSUE TITLE
Question: Does Modern Search collect telemetry and if so can it be turned off?

### ISSUE THREAD

**Issue by alexabramkin** [pnp/sp-dev-solutions#418]
#### Category
- [x] Question
Does Modern Search collect telemetry and if so can it be turned off?

**Comment by wobba** [comment]
Some of the PnP controls we use might collect telemetry, but we have no logging ourselves in the web parts. For the PnP controls we could expose an option to turn it off.

What's your requirement/scenario?

**Comment by alexabramkin** [comment]
Thank you for the info, will move to the correct repo. This is just a question we got asked by information security folks prior to the production deploy. Would be nice if that was an option, will let you know once have more info on requirements.
