### ISSUE TITLE
Enhancement proposal for Modern Search: Expose an option to turn off telemetry collection by PnP controls in use.

### ISSUE THREAD

**Issue by alexabramkin** [pnp/sp-dev-solutions#419]
- [x] Enhancement
Nice to have: Expose an option to turn off telemetry collection by PnP controls in use.

**Comment by FranckyC** [comment]
Hi @alexabramkin just for my information, is it because of security/performances concerns or something else? Thanks.

**Comment by alexabramkin** [comment]
Internal informational security folks not being warm to the idea of use info going outside of organization.

**Comment by FranckyC** [comment]
Could I ask you to create the issue in the correct repo https://github.com/microsoft-search/pnp-modern-search/issues? Thanks.

**Comment by alexabramkin** [comment]
I though I did  - haha: will do 👍

**Comment by alexabramkin** [comment]
Created issue [315](https://github.com/microsoft-search/pnp-modern-search/issues/315) in correct repo.
