### ISSUE TITLE
Modern search result spfx webpart keeps firing PostQuery and browser errors Out of Memory

### ISSUE THREAD

**Issue by manishkaushal2015** [pnp/sp-dev-solutions#420]
#### Category
- [x] Question
- [x] Bug

Deployed sppkg file pnp-modern-search-parts.sppkg from the released version 3.13.0.0

#### Expected or Desired Behavior
Search box connected to SearchResults webpart. User searching in search box should yield results in Search Results webpart. 

#### Observed Behavior
Search results appear on user input in search box but search results webpart keep loading. Record counts are shown correctly in Vertical Search webpart. Results webpart keeps firing search Post Queries without stopping. Please refer to screenshot attached for the number of queries fired for almost 3000 search results. The result is that it finally bringing down the webpage to out of memory. Tested on Chrome browser,  got out of memory error. Removed webparts re-added.
Can you please direct me to a way of finding the underlying issue? Could it be due to a recent commit in code version 3.13?

#### Steps to Reproduce########
SP Tenant type: Developer tenant
Downloaded package pnp-modern-search-parts.sppkg released version 3.13.0.0
Deployed this package to tenant apps catalog, deployment setting available to all sites enabled.
Configured Search Box, Search Results and Refiner webparts as directed in the documentation.
Search results webpart should display results and not keep displaying data loader till the page dies.

 
Looking forward to your prompt help.

**Comment by manishkaushal2015** [comment]
![Error_SearchResults](https://user-images.githubusercontent.com/12091712/84999112-13948c80-b194-11ea-9ffe-991474714391.JPG)

**Comment by manishkaushal2015** [comment]
![Error_SearchResults2](https://user-images.githubusercontent.com/12091712/84999781-f57b5c00-b194-11ea-9494-e49fdbb57cbc.JPG)

**Comment by manishkaushal2015** [comment]
Results found 3240
No of Process Query Requests 3930 and still going on....

**Comment by wobba** [comment]
Issue logged in wrong repo.  Webparts live in https://github.com/microsoft-search/pnp-modern-search

**Comment by manishkaushal2015** [comment]
Added this issue to the right location https://github.com/microsoft-search/pnp-modern-search/issues/320
