### ISSUE TITLE
Something changed in Dynamic Webpart Property 

### ISSUE THREAD

**Issue by AvniBhatt** [pnp/sp-dev-solutions#423]
Node Version : 8.16.1
I was using below code to get the selected menu item from the property pane:
`let selectedMenuItem = this._dynamicDataService.getDataSourceValue(this.properties.menuItem, this.properties.sourceId, this.properties.propertyId, this.properties.propertyPath);`

and in return, i used to get the selcted menu. Since yesterday something has changed and now, i am getting this value under:
`selectedMenuItem.menuItem`

Has it something to do with "DynamicDataService"? as I am getting the same issue wherever Dynamic Data Service is used. Other web parts which does not involve DynamicDataService works fine.

**Comment by wobba** [comment]
Could be related to https://github.com/SharePoint/sp-dev-docs/issues/5947

**Comment by AvniBhatt** [comment]
Yes @wobba , it was the same issue. Thank you!

**Comment by wobba** [comment]
So we can close this issue?

**Comment by AvniBhatt** [comment]
Yes, closing the issue.
