### ISSUE TITLE
No results from search box (nothing changed)

### ISSUE THREAD

**Issue by hsantan** [pnp/sp-dev-solutions#424]
#### Category
- [X] Question
- [ ] Bug
- [] Enhancement

#### Expected or Desired Behavior

I'm using the version 3.7.0.0 on my modern team site and its configured in my page one Search Box web part and one Search Results, Search Results web parts was retrieving results from Search box. But in this week not anymore

#### Observed Behavior

When you put default results to retrieve something like "* " directly in results search web part works fine. Just when you type something in search box nothing happens

Someone knows whats can be happening? 
I've been testing in different tenants and happened in all tenant that I tested.

**Comment by wobba** [comment]
Wrong repo. Check issue at https://github.com/microsoft-search/pnp-modern-search/issues/325
