### ISSUE TITLE
Issue to get Search results web part based on query string from URL page

### ISSUE THREAD

**Issue by yassineelghouat** [pnp/sp-dev-solutions#425]
#### Category
- [x] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

We have a modern sharepoint page with a search box and a search results web parts
We want to know if we can retrieve search results from a URL parameter
/sites/<SiteName>/Pages/Searchpage.aspx?k=<SearchResult>

hanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
See https://github.com/microsoft-search/pnp-modern-search/issues/325.
