### ISSUE TITLE
Impossible to install extensibility library 

### ISSUE THREAD

**Issue by MaximeChofardet** [pnp/sp-dev-solutions#435]
After successfully adding & deploying the package "pnp-modern-search-parts.sppkg" in a site collection app catalog, I am unable to deploy with success package "pnp-modern-search-extensibility-library.sspkg".
Repro steps : 
- Package app np-modern-search-extensibility-library
- Add the package in the dedicated site collection app catalog
- Try to deploy the app  => No error message

When returning to "Site Contents", the app stay blurred as below : 
![blurrd](https://user-images.githubusercontent.com/36511028/91851991-6abce000-ec60-11ea-8bea-326afaa0cb0e.PNG)

Could you please indicate us what is the issue.

Thanks in advance,

**Comment by wobba** [comment]
Anything PnP modern search should be logged at https://github.com/microsoft-search with extensibility docs located at https://microsoft-search.github.io/pnp-modern-search/search-extensibility-library/getting-started/

**Comment by MaximeChofardet** [comment]
Related issue  : 
https://github.com/microsoft-search/pnp-modern-search/issues/446
