### ISSUE TITLE
Get Error making HttpClient request in queryable[500] from Result web part

### ISSUE THREAD

**Issue by KMCSebastian** [pnp/sp-dev-solutions#436]
#### Category
- [ ] Question
- [X] Bug
- [] Enhancement

#### Expected or Desired Behavior
Should return results as normal.

#### Observed Behavior

Results web part becomes a red box with a 500 error instead of return results from the query using the Search Bar web part. 
![image](https://user-images.githubusercontent.com/70582706/91854145-e9962680-ec28-11ea-941a-0d1a28c8edeb.png). Query runs with no issue when using Search Query Tool.
![image](https://user-images.githubusercontent.com/70582706/91862332-6e863d80-ec33-11ea-9595-144b42963dae.png)

#### Steps to Reproduce

use a Search Results Web Part. Query returns this same error for multiple users.

**Comment by wobba** [comment]
Kind of hard to debug this, as I cannot repro. How have you configured your web parts? And you could look at the XHR call in debug tool in your browser to look at the actual request and compare with the query tool.

**Comment by wobba** [comment]
Also, PnP modern search repo is at https://github.com/microsoft-search/pnp-modern-search, and include what version you are testing.

**Comment by KMCSebastian** [comment]
We are using the webparts on a site page. A search box is connected to the result webpart using the search box's search query property. A Filter webpart is getting refineables  mapped to ows_q_text from libraries. We are currently using 3.14 of PnP. XHR does not seem to show the request but the error.
  
![image](https://user-images.githubusercontent.com/70582706/92119662-b9cc5780-edbd-11ea-955e-090b2aaf101b.png)
