### ISSUE TITLE
PNP Modern Search Webpart - filter results based on column value of a library

### ISSUE THREAD

**Issue by Namrata99sah** [pnp/sp-dev-solutions#446]
#### Category
- [x] Question
- [ ] Bug
- [] Enhancement

#### Expected or Desired Behavior

I'm using PNP modern search web part i.e. search box and search results web part. I want to get a search result based on one single library. There are two cases here user search based on the 'Title' column or 'CaseNumber' column of the library. How can I format the KQL query to achieve this?
Currently, the Query template is : {searchTerms} (ParentLink:{/LibraryName/} AND (ContentTypeId:{0x01234*}

There are few columns which contain related list item i.e. custom column to relate one item to another. For eg, If the user search with ID - 1234, it returns 2 results, one the item itself and 2nd the related item as it searches in the whole library.

OR, if there a way I can exclude the column from the search using any filters etc.

Thanks for your contribution! Sharing is caring.

**Comment by wobba** [comment]
PnP Modern search issues to be logged at https://github.com/microsoft-search/pnp-modern-search/issues
