### ISSUE TITLE
Regex in column handlebars

### ISSUE THREAD

**Issue by paylord** [pnp/sp-dev-solutions#447]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I am trying to provide a link in the results to the properties of a document.  I have tried a variety of ways:
SiteUrl  - always seems to be empty for a library
Path  - good start but only need the first bit of the URL
ParentLink  - even better but again need to tweak the actual page (AllItems.aspx to EditForm.aspx)

EditForm.aspx?ID=<ListItemID> - this is ugly but works - open to a better suggestion but prefer a simple one for now - will consider custom SPFx in future.

#### Observed Behavior

I have been trying to use the regex helper to just get the URL for the library the returned document is in.  This is by creating a custom handlebar for a specific column.

{{regex "/(.*\/)/g" ParentLink}}

The above just seems to return a hyphen?

I appreciate this may just be my lack of knowledge or understanding as opposed to a bug but there seems to be very little documentation I can find to research further.

Thanks :)

**Comment by wobba** [comment]
Which solution is your question about?

**Comment by paylord** [comment]
Ha - sorry Mikael.  This is the search results web part.  Using the tabular list layout.  Under manage columns I am trying to apply a custom handlebar to a single column and use the regex helper.

**Comment by wobba** [comment]
Modern search questions should be logged at https://github.com/microsoft-search/pnp-modern-search. Check the issues list as I'm sure something similar is logged and replied to before. And it's a handlebar problem for you, not webpart per say ;)

**Comment by paylord** [comment]
Doh - no wonder you were questioning which solution I was referring to!

Yes, I agree this is more about me knowing how to use the regex helper in handlebars rather than an issue with the web part - just struggling to find any documentation on it as I believe it is custom one added on top of the standard handlebars helpers 👍

**Comment by wobba** [comment]
See this one: https://github.com/microsoft-search/pnp-modern-search/issues/460#issuecomment-689011472

**Comment by paylord** [comment]
@wobba Ha thanks - I obviously need to improve my search ability - searching for "handlebars regex" does not find that in either Open nor Closed.  However, your suggestion is exactly what I was looking for 👍

**Comment by wobba** [comment]
@paylord We don't have a regex helper, but we support most of the handlebar helpers (version dependent and we cannot upgrade due to bundling issues).

**Comment by paylord** [comment]
@wobba I am easily confused - I read the reference on this page https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/ as there being a regex helper:

{{regex <exp> <string> }} | Match a regular expression against a string.
-- | --

**Comment by wobba** [comment]
You are right 🤦‍♂️ I need to read the docs better, and see it in the code as well when you mention it.
