### ISSUE TITLE
Does LinksAndHandlebarsTemplate work on on prem 2019

### ISSUE THREAD

**Issue by JoelHJ** [pnp/sp-dev-solutions#465]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Does the LinksAndHandlebarsTemplate work on On prem 2019?

**Comment by wobba** [comment]
No, it's built using SPFx v1.10, while 2019 support v1.4.1. Seems a compatible version was available April 2018 via this commit https://github.com/pnp/sp-dev-solutions/commit/42cb46d3b3a6d615d7303ef8d01b29cc7fda794a#diff-7d61d98c656bba42c48b8e96a46f41d4b9f67187eb640f3557292100b75f4d35
