### ISSUE TITLE
Open links in search results in client app 

### ISSUE THREAD

**Issue by carry2web** [pnp/sp-dev-solutions#475]
Make open in client application a choice in the generated results links, now web=1 is appended to each link. 
While many prefer open in client app.
Can this be changed or made a setting in the search results webpart?
I have seen the response to https://github.com/pnp/sp-dev-solutions/issues/79#issuecomment-472851795
That answers for client ms-word. For other office formats/other file formats ms-excel etc. should be put in front?
#### Category
- [ ] Question
- [ ] Bug
- [x] Enhancement

**Comment by wobba** [comment]
If your question is about the PnP Modern Search web parts, then head over to https://github.com/microsoft-search/pnp-modern-search/discussions and propose this. You can also modify your handlebar template to achieve the same. Also, protocol handlers do not work for all operating systems and devices.
