### ISSUE TITLE
Replace Author in List template with custom managed metadata field value

### ISSUE THREAD

**Issue by taliamath** [pnp/sp-dev-solutions#516]
#### Category
- [x] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I would like the default Author slot in a custom template based on the List template to display a custom RefinableString value or values instead of the AuthorOWSUSER, OR I would like it to appear exactly the same as if that were happening. 

#### Observed Behavior

When I try to add it as a new slot or replace the Author slot, it does not work. 

#### Steps to Reproduce

I tried replacing AuthorOWSUSER with RefinableString100 in the Layout slots area. I also tried adding a custom field, "Creator," using RefinableString100. I also tried using Autoowstaxid[name of the taxonomy field]. None of those things worked.

**Comment by wobba** [comment]
I suggest you ask this question over at https://github.com/microsoft-search/pnp-modern-search/discussions
