### ISSUE TITLE
References to Canary endpoints in Graph Sample for Pages API

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-solutions#571]
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Check the endpoints.

#### Observed Behavior

Reading sample: https://github.com/pnp/sp-dev-solutions/blob/master/solutions/PagesAPISolution/PowerShell/PagesController.ps1 I have noticed this refers to graph endpoints that are the dogfood version, is this intended?

Also, can the sample (although tempted to write one) use the new Graph PowerShell V2 SDK? 

#### Steps to Reproduce

Read the script, references on line: 
https://github.com/pnp/sp-dev-solutions/blob/847e54491cfb08f28f979709cd359d30c77b60bb/solutions/PagesAPISolution/PowerShell/PagesController.ps1#L136

Thanks for your contribution! Sharing is caring.

**Comment by sangle7** [comment]
Thanks for pointing it out. It's a typo and should be the public endpoint. I'll raise a PR to resolve it :)

Yes the Pages API related endpoints can be used with the Graph PowerShell V2 SDK (latest version)
