### ISSUE TITLE
RefinableLinks? Issue with RefinableString and lookup links

### ISSUE THREAD

**Issue by PowerProvoker** [pnp/sp-dev-solutions#582]
Hey folks - looking through some guidance material from multiple posts/blogs etc - you should be able to map a lookup column to RefinableString in order to display on Results web parts.

While this is true, it seems to not work well when the lookup column contains links.

For example - I have a lookup column 'Related Documents' where a user can select multiple documents. Mapping this to 'RefinableString23'.

e.g. from below: 

```<div class="Related">
            Related Documents: <a href="https://myste.sharepoint.cmo/sites/thissite/alibrary/{{slot item @root.slots.Related}}">{{slot item @root.slots.Related}}</a> 
        </div>
```

This however, renders as a single link for all the text contained within RefinableString23 (which is associated with .slots.Related).

I could loop through somehow but that seems a little onerous. Is there perhaps a different way to render this out to show multiple, comma separated links?

**Comment by wobba** [comment]
If this is related to pnp modern search web parts you are better off asking in the discussion over at https://github.com/microsoft-search/pnp-modern-search

**Comment by PowerProvoker** [comment]
@wobba oh gosh my mistake! I asked in the wrong channel. I will remove this.
